In [2]:
import os

os.chdir("/Users/rahulgupta/Desktop/C-RAG")

In [3]:
import pandas as pd

In [4]:
answers_df = pd.read_csv('app/assets/raw/datasets/stackoverflow/Answers.csv')
questions_df = pd.read_csv('app/assets/raw/datasets/stackoverflow/Questions.csv')
tags_df = pd.read_csv('app/assets/raw/datasets/stackoverflow/Tags.csv')

In [5]:
answers_df.head()

,Id,OwnerUserId,CreationDate,ParentId,Score,Body
0,497,50.0,2008-08-02T16:56:53Z,469,4,<p>open up a terminal (Applications-&gt;Utilit...
1,518,153.0,2008-08-02T17:42:28Z,469,2,<p>I haven't been able to find anything that d...
2,536,161.0,2008-08-02T18:49:07Z,502,9,<p>You can use ImageMagick's convert utility f...
3,538,156.0,2008-08-02T18:56:56Z,535,23,<p>One possibility is Hudson. It's written in...
4,541,157.0,2008-08-02T19:06:40Z,535,20,"<p>We run <a href=""http://buildbot.net/trac"">B..."

In [6]:
questions_df.head()

,Id,OwnerUserId,CreationDate,Score,Title,Body
0,469,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
1,502,147.0,2008-08-02T17:01:58Z,27,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...
2,535,154.0,2008-08-02T18:43:54Z,40,Continuous Integration System for a Python Cod...,<p>I'm starting work on a hobby project with a...
3,594,116.0,2008-08-03T01:15:08Z,25,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...
4,683,199.0,2008-08-03T13:19:16Z,28,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...

In [7]:
tags_df.head()

    Id        Tag
0  469     python
1  469        osx
2  469      fonts
3  469  photoshop
4  502     python

In [7]:
print("Questions Shape:", questions_df.shape)
print("Answers Shape:", answers_df.shape)

Questions Shape: (607282, 6)
Answers Shape: (987122, 6)

In [8]:
print(questions_df.columns)
print(answers_df.columns)

Index(['Id', 'OwnerUserId', 'CreationDate', 'Score', 'Title', 'Body'], dtype='str')
Index(['Id', 'OwnerUserId', 'CreationDate', 'ParentId', 'Score', 'Body'], dtype='str')

In [8]:
from app.ingestion.preprocessing import (
    load_data,
    select_best_answers,
    merge_questions_answers
)

questions, answers = load_data(
    "app/assets/raw/datasets/stackoverflow/Questions.csv",
    "app/assets/raw/datasets/stackoverflow/Answers.csv"
)

best_answers = select_best_answers(answers)

merged_df = merge_questions_answers(
    questions,
    best_answers
)

print(merged_df.shape)
merged_df.head()

(539238, 12)

,Id_question,OwnerUserId_question,CreationDate_question,Score_question,Title,Body_question,ParentId,Id_answer,OwnerUserId_answer,CreationDate_answer,Score_answer,Body_answer
0,469,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...,469,3040,457.0,2008-08-06T03:01:23Z,12,<p>Unfortunately the only API that isn't depre...
1,502,147.0,2008-08-02T17:01:58Z,27,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...,502,7090,13.0,2008-08-10T08:08:33Z,25,<p>ImageMagick delegates the PDF->bitmap conve...
2,535,154.0,2008-08-02T18:43:54Z,40,Continuous Integration System for a Python Cod...,<p>I'm starting work on a hobby project with a...,535,538,156.0,2008-08-02T18:56:56Z,23,<p>One possibility is Hudson. It's written in...
3,594,116.0,2008-08-03T01:15:08Z,25,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...,594,595,116.0,2008-08-03T01:17:36Z,25,<p>The canonical way is to use the built-in cu...
4,683,199.0,2008-08-03T13:19:16Z,28,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...,683,57833,4702.0,2008-09-11T22:42:14Z,29,<p>Using a list comprehension would build a te...

In [10]:
print(f"-----questions Body------\n{questions_df['Body'].iloc[0]}", end="\n\n")

print(f"-----answers Body-------\n{answers_df['Body'].iloc[0]}", end="\n\n")

-----questions Body------
<p>I am using the Photoshop's javascript API to find the fonts in a given PSD.</p>

<p>Given a font name returned by the API, I want to find the actual physical font file that that font name corresponds to on the disc.</p>

<p>This is all happening in a python program running on OSX so I guess I'm looking for one of:</p>

<ul>
<li>Some Photoshop javascript</li>
<li>A Python function</li>
<li>An OSX API that I can call from python</li>
</ul>


-----answers Body-------
<p>open up a terminal (Applications-&gt;Utilities-&gt;Terminal) and type this in:</p>

<pre><code>locate InsertFontHere<br></code></pre>

<p>This will spit out every file that has the name you want.</p>

<p>Warning: there may be alot to wade through.</p>

In [11]:
from app.ingestion.html_cleaning import clean_html
sample = merged_df["Body_question"].iloc[0]


print(clean_html(sample))

I am using the Photoshop's javascript API to find the fonts in a given PSD.
Given a font name returned by the API, I want to find the actual physical font file that that font name corresponds to on the disc.
This is all happening in a python program running on OSX so I guess I'm looking for one of:
Some Photoshop javascript
A Python function
An OSX API that I can call from python

In [9]:
from app.ingestion.creat_doc import create_documents

documents = create_documents(merged_df)
print(f"Number of documents created: {len(documents)}")
print(f"Sample Document:\n{documents[0]}")

Number of documents created: 539238
Sample Document:
page_content='
TITLE:
How can I find the full path to a font from its display name on a Mac?

QUESTION:
I am using the Photoshop's javascript API to find the fonts in a given PSD.
Given a font name returned by the API, I want to find the actual physical font file that that font name corresponds to on the disc.
This is all happening in a python program running on OSX so I guess I'm looking for one of:
Some Photoshop javascript
A Python function
An OSX API that I can call from python

ANSWER:
Unfortunately the only API that isn't deprecated is located in the ApplicationServices framework, which doesn't have a bridge support file, and thus isn't available in the bridge. If you're wanting to use ctypes, you can use ATSFontGetFileReference after looking up the ATSFontRef.
Cocoa doesn't have any native support, at least as of 10.5, for getting the location of a font.
' metadata={'question_id': 469, 'answer_id': 3040, 'question_score': 21, 'answer_score': 12, 'source': 'stackoverflow'}

In [13]:
print(documents[0].metadata)

{'question_id': 469, 'answer_id': 3040, 'question_score': 21, 'answer_score': 12, 'source': 'stackoverflow'}

In [10]:
documents

[Document(metadata={'question_id': 469, 'answer_id': 3040, 'question_score': 21, 'answer_score': 12, 'source': 'stackoverflow'}, page_content="\nTITLE:\nHow can I find the full path to a font from its display name on a Mac?\n\nQUESTION:\nI am using the Photoshop's javascript API to find the fonts in a given PSD.\nGiven a font name returned by the API, I want to find the actual physical font file that that font name corresponds to on the disc.\nThis is all happening in a python program running on OSX so I guess I'm looking for one of:\nSome Photoshop javascript\nA Python function\nAn OSX API that I can call from python\n\nANSWER:\nUnfortunately the only API that isn't deprecated is located in the ApplicationServices framework, which doesn't have a bridge support file, and thus isn't available in the bridge. If you're wanting to use ctypes, you can use ATSFontGetFileReference after looking up the ATSFontRef.\nCocoa doesn't have any native support, at least as of 10.5, for getting the location of a font.\n"),
 Document(metadata={'question_id': 502, 'answer_id': 7090, 'question_score': 27, 'answer_score': 25, 'source': 'stackoverflow'}, page_content="\nTITLE:\nGet a preview JPEG of a PDF on Windows?\n\nQUESTION:\nI have a cross-platform (Python) application which needs to generate a JPEG preview of the first page of a PDF.\nOn the Mac I am spawning\nsips\n.  Is there something similarly simple I can do on Windows?\n\nANSWER:\nImageMagick delegates the PDF->bitmap conversion to GhostScript anyway, so here's a command you can use (it's based on the actual command listed by the\n[CODE]\nps:alpha\n[/CODE]\ndelegate in ImageMagick, just adjusted to use JPEG as output):\n[CODE]\ngs -q -dQUIET -dPARANOIDSAFER -dBATCH -dNOPAUSE -dNOPROMPT \\\n-dMaxBitmap=500000000 -dLastPage=1 -dAlignToPixels=0 -dGridFitTT=0 \\\n-sDEVICE=jpeg -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r72x72 \\\n-sOutputFile=$OUTPUT -f$INPUT\n[/CODE]\nwhere\n[CODE]\n$OUTPUT\n[/CODE]\nand\n[CODE]\n$INPUT\n[/CODE]\nare the output and input filenames. Adjust the\n[CODE]\n72x72\n[/CODE]\nto whatever resolution you need. (Obviously, strip out the backslashes if you're writing out the whole command as one line.)\nThis is good for two reasons:\nYou don't need to have ImageMagick installed anymore. Not that I have anything against ImageMagick (I love it to bits), but I believe in simple solutions.\nImageMagick does a two-step conversion. First PDF->PPM, then PPM->JPEG. This way, the conversion is one-step.\nOther things to consider: with the files I've tested, PNG compresses better than JPEG. If you want to use PNG, change the\n[CODE]\n-sDEVICE=jpeg\n[/CODE]\nto\n[CODE]\n-sDEVICE=png16m\n[/CODE]\n.\n"),
 Document(metadata={'question_id': 535, 'answer_id': 538, 'question_score': 40, 'answer_score': 23, 'source': 'stackoverflow'}, page_content="\nTITLE:\nContinuous Integration System for a Python Codebase\n\nQUESTION:\nI'm starting work on a hobby project with a python codebase and would like to set up some form of continuous integration (i.e. running a battery of test-cases each time a check-in is made and sending nag e-mails to responsible persons when the tests fail) similar to CruiseControl or TeamCity.\nI realize I could do this with hooks in most VCSes, but that requires that the tests run on the same machine as the version control server, which isn't as elegant as I would like. Does anyone have any suggestions for a small, user-friendly, open-source continuous integration system suitable for a Python codebase?\n\nANSWER:\nOne possibility is Hudson.  It's written in Java, but there's integration with Python projects:\nHudson embraces Python\nI've never tried it myself, however.\n(\nUpdate\n, Sept. 2011: After a trademark dispute Hudson has been renamed to\nJenkins\n.)\n"),
 Document(metadata={'question_id': 594, 'answer_id': 595, 'question_score': 25, 'answer_score': 25, 'source': 'stackoverflow'}, page_content="\nTITLE:\ncx_Oracle: How do I iterate over a result set?\n\nQUESTION:\nThere are several ways to iterate over a result set. What are the tradeoff of each?\n\nANSWER:\nThe canonical way is to use the built-in cursor iterator.\n[CODE]\ncurs.execute('select * from people')\nfor row in curs:\nprint row\n[/CODE]\nYou can use\n[CODE]\nfetchall()\n[/CODE]\nto get all rows at once.\n[CODE]\nfor row in curs.fetchall():\nprint row\n[/CODE]\nIt can be convenient to use this to create a Python list containing the values returned:\n[CODE]\ncurs.execute('select first_name from people')\nnames = [row[0] for row in curs.fetchall()]\n[/CODE]\nThis can be useful for smaller result sets, but can have bad side effects if the result set is large.\nYou have to wait for the entire result set to be returned to\nyour client process.\nYou may eat up a lot of memory in your client to hold\nthe built-up list.\nIt may take a while for Python to construct and deconstruct the\nlist which you are going to immediately discard anyways.\nIf you know there's a single row being returned in the result set you can call\n[CODE]\nfetchone()\n[/CODE]\nto get the single row.\n[CODE]\ncurs.execute('select max(x) from t')\nmaxValue = curs.fetchone()[0]\n[/CODE]\nFinally, you can loop over the result set fetching one row at a time.  In general, there's no particular advantage in doing this over using the iterator.\n[CODE]\nrow = curs.fetchone()\nwhile row:\nprint row\nrow = curs.fetchone()\n[/CODE]\n"),
 Document(metadata={'question_id': 683, 'answer_id': 57833, 'question_score': 28, 'answer_score': 29, 'source': 'stackoverflow'}, page_content="\nTITLE:\nUsing 'in' to match an attribute of Python objects in an array\n\nQUESTION:\nI don't remember whether I was dreaming or not but I seem to recall there being a function which allowed something like,\n[CODE]\nfoo in iter_attr(array of python objects, attribute name)\n[/CODE]\nI've looked over the docs but this kind of thing doesn't fall under any obvious listed headers\n\nANSWER:\nUsing a list comprehension would build a temporary list, which could eat all your memory if the sequence being searched is large. Even if the sequence is not large, building the list means iterating over the whole of the sequence before\n[CODE]\nin\n[/CODE]\ncould start its search.\nThe temporary list can be avoiding by using a generator expression:\n[CODE]\nfoo = 12\nfoo in (obj.id for obj in bar)\n[/CODE]\nNow, as long as\n[CODE]\nobj.id == 12\n[/CODE]\nnear the start of\n[CODE]\nbar\n[/CODE]\n, the search will be fast, even if\n[CODE]\nbar\n[/CODE]\nis infinitely long.\nAs @Matt suggested, it's a good idea to use\n[CODE]\nhasattr\n[/CODE]\nif any of the objects in\n[CODE]\nbar\n[/CODE]\ncan be missing an\n[CODE]\nid\n[/CODE]\nattribute:\n[CODE]\nfoo = 12\nfoo in (obj.id for obj in bar if hasattr(obj, 'id'))\n[/CODE]\n"),
 Document(metadata={'question_id': 742, 'answer_id': 33957, 'question_score': 30, 'answer_score': 36, 'source': 'stackoverflow'}, page_content="\nTITLE:\nClass views in Django\n\nQUESTION:\nDjango\nview points to a function, which can be a problem if you want to change only a bit of functionality. Yes, I could have million keyword arguments and even more if statements in the function, but I was thinking more of an object oriented approach.\nFor example, I have a page that displays a user. This page is very similar to page that displays a group, but it's still not so similar to just use another data model. Group also has members etc...\nOne way would be to point views to class methods and then extend that class. Has anyone tried this approach or has any other idea?\n\nANSWER:\nI've created and used my own generic view classes, defining\n[CODE]\n__call__\n[/CODE]\nso an instance of the class is callable.  I really like it; while Django's generic views allow some customization through keyword arguments, OO generic views (if their behavior is split into a number of separate methods) can have much more fine-grained customization via subclassing, which lets me repeat myself a lot less.  (I get tired of rewriting the same create/update view logic anytime I need to tweak something Django's generic views don't quite allow).\nI've posted some code at\ndjangosnippets.org\n.\nThe only real downside I see is the proliferation of internal method calls, which may impact performance somewhat. I don't think this is much of a concern; it's rare that Python code execution would be your performance bottleneck in a web app.\nUPDATE\n: Django's own\ngeneric views\nare now class-based.\nUPDATE\n: FWIW, I've changed my opinion on class-based views since this answer was written. After having used them extensively on a couple of projects, I feel they tend to lead to code that is satisfyingly DRY to write, but very hard to read and maintain later, because functionality is spread across so many different places, and subclasses are so dependent on every implementation detail of the superclasses and mixins. I now feel that\nTemplateResponse\nand view decorators is a better answer for decomposing view code.\n"),
 Document(metadata={'question_id': 766, 'answer_id': 1619, 'question_score': 20, 'answer_score': 17, 'source': 'stackoverflow'}, page_content="\nTITLE:\nPython and MySQL\n\nQUESTION:\nI can get Python to work with Postgresql but I cannot get it to work with MySQL. The main problem is that on the shared hosting account I have I do not have the ability to install things such as Django or PySQL, I generally fail when installing them on my computer so maybe it's good I can't install on the host.\nI found\nbpgsql\nreally good because it does not require an install, it's a single file that I can look at, read and then call the functions of. Does anybody know of something like this for MySQL?\n\nANSWER:\nMySQLdb is what I have used before.\nIf you host is using Python version 2.5 or higher, support for sqlite3 databases is built in (sqlite allows you to have a relational database that is simply a file in your filesystem).  But buyer beware, sqlite is not suited for production, so it may depend what you are trying to do with it.\nAnother option may be to call your host and complain, or change hosts.  Honestly these days, any self respecting web host that supports python and mysql ought to have MySQLdb pre installed.\n"),
 Document(metadata={'question_id': 773, 'answer_id': 7286, 'question_score': 256, 'answer_score': 394, 'source': 'stackoverflow'}, page_content='\nTITLE:\nHow do I use Python\'s itertools.groupby()?\n\nQUESTION:\nI haven\'t been able to find an understandable explanation of how to actually use Python\'s\n[CODE]\nitertools.groupby()\n[/CODE]\nfunction.  What I\'m trying to do is this:\nTake a list - in this case, the children of an objectified\n[CODE]\nlxml\n[/CODE]\nelement\nDivide it into groups based on some criteria\nThen later iterate over each of these groups separately.\nI\'ve reviewed\nthe documentation\n, and\nthe examples\n, but I\'ve had trouble trying to apply them beyond a simple list of numbers.\nSo, how do I use of\n[CODE]\nitertools.groupby()\n[/CODE]\n?  Is there another technique I should be using?  Pointers to good "prerequisite" reading would also be appreciated.\n\nANSWER:\nAs Sebastjan said,\nyou first have to sort your data. This is important.\nThe part I didn\'t get is that in the example construction\n[CODE]\ngroups = []\nuniquekeys = []\nfor k, g in groupby(data, keyfunc):\ngroups.append(list(g))    # Store group iterator as a list\nuniquekeys.append(k)\n[/CODE]\n[CODE]\nk\n[/CODE]\nis the current grouping key, and\n[CODE]\ng\n[/CODE]\nis an iterator that you can use to iterate over the group defined by that grouping key. In other words, the\n[CODE]\ngroupby\n[/CODE]\niterator itself returns iterators.\nHere\'s an example of that, using clearer variable names:\n[CODE]\nfrom itertools import groupby\nthings = [("animal", "bear"), ("animal", "duck"), ("plant", "cactus"), ("vehicle", "speed boat"), ("vehicle", "school bus")]\nfor key, group in groupby(things, lambda x: x[0]):\nfor thing in group:\nprint "A %s is a %s." % (thing[1], key)\nprint " "\n[/CODE]\nThis will give you the output:\nA bear is a animal.\nA duck is a animal.\nA cactus is a plant.\nA speed boat is a vehicle.\nA school bus is a vehicle.\nIn this example,\n[CODE]\nthings\n[/CODE]\nis a list of tuples where the first item in each tuple is the group the second item belongs to.\nThe\n[CODE]\ngroupby()\n[/CODE]\nfunction takes two arguments: (1) the data to group and (2) the function to group it with.\nHere,\n[CODE]\nlambda x: x[0]\n[/CODE]\ntells\n[CODE]\ngroupby()\n[/CODE]\nto use the first item in each tuple as the grouping key.\nIn the above\n[CODE]\nfor\n[/CODE]\nstatement,\n[CODE]\ngroupby\n[/CODE]\nreturns three (key, group iterator) pairs - once for each unique key. You can use the returned iterator to iterate over each individual item in that group.\nHere\'s a slightly different example with the same data, using a list comprehension:\n[CODE]\nfor key, group in groupby(things, lambda x: x[0]):\nlistOfThings = " and ".join([thing[1] for thing in group])\nprint key + "s:  " + listOfThings + "."\n[/CODE]\nThis will give you the output:\nanimals: bear and duck.\nplants: cactus.\nvehicles: speed boat and school bus.\n'),
 Document(metadata={'question_id': 972, 'answer_id': 2982, 'question_score': 364, 'answer_score': 576, 'source': 'stackoverflow'}, page_content='\nTITLE:\nAdding a Method to an Existing Object Instance\n\nQUESTION:\nI\'ve read that it is possible to add a method to an existing object (e.g. not in the class definition) in\nPython\n, I think this is called\nMonkey Patching\n(or in some cases\nDuck Punching\n). I understand that it\'s not always a good decision to do so. But, how might one do this?\nUPDATE 8/04/2008 00:21:01 EST:\nThat\nlooks like a good answer John Downey, I tried it but it appears that it ends up being not a\ntrue\nmethod.\nYour example defines the new patch function with an argument of\n[CODE]\nself\n[/CODE]\n, but if you write actual code that way, the now patched class method asks for an argument named\n[CODE]\nself\n[/CODE]\n(it doesn\'t automagically recognize it as the object to which it is supposed to bind, which is what would happen if defined within the class definition), meaning you have to call\n[CODE]\nclass.patch(obj)\n[/CODE]\ninstead of just\n[CODE]\nclass.patch()\n[/CODE]\nif you want the same functionality as a\ntrue\nmethod.\nIt looks like Python isn\'t really treating it as a method, but more just as a variable which happens to be a function\n(and as such is callable).  Is there any way to attach an actual method to a class?\nOh, and Ryan,\nthat\nisn\'t exactly what I was looking for (it isn\'t a builtin functionality), but it is quite cool nonetheless.\n\nANSWER:\nIn Python, there is a difference between functions and bound methods.\n[CODE]\n>>> def foo():\n...     print "foo"\n...\n>>> class A:\n...     def bar( self ):\n...         print "bar"\n...\n>>> a = A()\n>>> foo\n<function foo at 0x00A98D70>\n>>> a.bar\n<bound method A.bar of <__main__.A instance at 0x00A9BC88>>\n>>>\n[/CODE]\nBound methods have been "bound" (how descriptive) to an instance, and that instance will be passed as the first argument whenever the method is called.\nCallables that are attributes of a class (as opposed to an instance) are still unbound, though, so you can modify the class definition whenever you want:\n[CODE]\n>>> def fooFighters( self ):\n...     print "fooFighters"\n...\n>>> A.fooFighters = fooFighters\n>>> a2 = A()\n>>> a2.fooFighters\n<bound method A.fooFighters of <__main__.A instance at 0x00A9BEB8>>\n>>> a2.fooFighters()\nfooFighters\n[/CODE]\nPreviously defined instances are updated as well (as long as they haven\'t overridden the attribute themselves):\n[CODE]\n>>> a.fooFighters()\nfooFighters\n[/CODE]\nThe problem comes when you want to attach a method to a single instance:\n[CODE]\n>>> def barFighters( self ):\n...     print "barFighters"\n...\n>>> a.barFighters = barFighters\n>>> a.barFighters()\nTraceback (most recent call last):\nFile "<stdin>", line 1, in <module>\nTypeError: barFighters() takes exactly 1 argument (0 given)\n[/CODE]\nThe function is not automatically bound when it\'s attached directly to an instance:\n[CODE]\n>>> a.barFighters\n<function barFighters at 0x00A98EF0>\n[/CODE]\nTo bind it, we can use the\nMethodType function in the types module\n:\n[CODE]\n>>> import types\n>>> a.barFighters = types.MethodType( barFighters, a )\n>>> a.barFighters\n<bound method ?.barFighters of <__main__.A instance at 0x00A9BC88>>\n>>> a.barFighters()\nbarFighters\n[/CODE]\nThis time other instances of the class have not been affected:\n[CODE]\n>>> a2.barFighters()\nTraceback (most recent call last):\nFile "<stdin>", line 1, in <module>\nAttributeError: A instance has no attribute \'barFighters\'\n[/CODE]\nMore information can be found by reading about\ndescriptors\nand\nmetaclass\nprogramming\n.\n'),
 Document(metadata={'question_id': 1476, 'answer_id': 13107, 'question_score': 251, 'answer_score': 204, 'source': 'stackoverflow'}, page_content="\nTITLE:\nHow do you express binary literals in Python?\n\nQUESTION:\nHow do you express an integer as a binary number with Python literals?\nI was easily able to find the answer for hex:\n[CODE]\n>>> 0x12AF\n4783\n>>> 0x100\n256\n[/CODE]\nand octal:\n[CODE]\n>>> 01267\n695\n>>> 0100\n64\n[/CODE]\nHow do you use literals to express binary in Python?\nSummary of Answers\nPython 2.5 and earlier: can express binary using\n[CODE]\nint('01010101111',2)\n[/CODE]\nbut not with a literal.\nPython 2.5 and earlier: there is\nno way\nto express binary literals.\nPython 2.6 beta: You can do like so:\n[CODE]\n0b1100111\n[/CODE]\nor\n[CODE]\n0B1100111\n[/CODE]\n.\nPython 2.6 beta: will also allow\n[CODE]\n0o27\n[/CODE]\nor\n[CODE]\n0O27\n[/CODE]\n(second character is the letter O) to represent an octal.\nPython 3.0 beta: Same as 2.6, but will no longer allow the older\n[CODE]\n027\n[/CODE]\nsyntax for octals.\n\nANSWER:\nFor reference—\nfuture\nPython possibilities:\nStarting with Python 2.6 you can express binary literals using the prefix\n0b\nor\n0B\n:\n[CODE]\n>>> 0b101111\n47\n[/CODE]\nYou can also use the new\nbin\nfunction to get the binary representation of a number:\n[CODE]\n>>> bin(173)\n'0b10101101'\n[/CODE]\nDevelopment version of the documentation:\nWhat's New in Python 2.6\n"),
 Document(metadata={'question_id': 1734, 'answer_id': 6161, 'question_score': 20, 'answer_score': 10, 'source': 'stackoverflow'}, page_content="\nTITLE:\nAny experiences with Protocol Buffers?\n\nQUESTION:\nI was just looking through some information about Google's\nprotocol buffers\ndata interchange format.  Has anyone played around with the code or even created a project around it?\nI'm currently using XML in a Python project for structured content created by hand in a text editor, and I was wondering what the general opinion was on Protocol Buffers as a user-facing input format.  The speed and brevity benefits definitely seem to be there, but there are so many factors when it comes to actually generating and processing the data.\n\nANSWER:\nProtocol buffers are intended to optimize communications between machines. They are really not intended for human interaction. Also, the format is binary, so it could not replace XML in that use case.\nI would also recommend\nJSON\nas being the most compact text-based format.\n"),

In [14]:
lengths = [
    len(doc.page_content)
    for doc in documents[:10000]
]

print("Min:", min(lengths))
print("Max:", max(lengths))
print("Avg:", sum(lengths)/len(lengths))

Min: 141
Max: 25560
Avg: 1524.8275

In [15]:
from app.ingestion.chunks_docs import chunk_documents

chunked_docs = chunk_documents(documents[:1000])

print("Original:", len(documents[:1000]))
print("Chunked :", len(chunked_docs))

Original: 1000
Chunked : 1282

In [16]:
import pickle

with open(
    "app/assets/processed/chunked_docs.pkl",
    
    "wb"
) as f:
    pickle.dump(
        chunked_docs,
        f
    )

print(
    f"Saved {len(chunked_docs)} chunks"
)

Saved 1282 chunks

In [17]:
type(chunked_docs[0])

langchain_core.documents.base.Document

In [18]:
chunked_docs[0]

Document(metadata={'question_id': 469, 'answer_id': 3040, 'question_score': 21, 'answer_score': 12, 'source': 'stackoverflow'}, page_content="\nTITLE:\nHow can I find the full path to a font from its display name on a Mac?\n\nQUESTION:\nI am using the Photoshop's javascript API to find the fonts in a given PSD.\nGiven a font name returned by the API, I want to find the actual physical font file that that font name corresponds to on the disc.\nThis is all happening in a python program running on OSX so I guess I'm looking for one of:\nSome Photoshop javascript\nA Python function\nAn OSX API that I can call from python\n\nANSWER:\nUnfortunately the only API that isn't deprecated is located in the ApplicationServices framework, which doesn't have a bridge support file, and thus isn't available in the bridge. If you're wanting to use ctypes, you can use ATSFontGetFileReference after looking up the ATSFontRef.\nCocoa doesn't have any native support, at least as of 10.5, for getting the location of a font.\n")

In [19]:
from app.embeddings.embeddings_model import get_embedding_model

embedding_model = get_embedding_model() 
embedding_model.encode("What is the list comprehension in Python?")

Loading BGE model into memory...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

array([-1.24588248e-03,  2.67008971e-03,  1.58403348e-02, -6.96188211e-02,
        8.35167915e-02,  4.94599603e-02, -1.95017774e-02, -2.78915316e-02,
       -2.83316635e-02,  2.48730765e-04, -2.45398879e-02,  5.35994433e-02,
       -5.94472289e-02, -2.09603123e-02,  1.59503333e-02,  9.55273136e-02,
        5.40709123e-02, -2.23763566e-03, -2.93456409e-02,  1.85204577e-03,
        2.16488987e-02,  1.40367560e-02, -1.15971016e-02, -1.04357079e-02,
       -1.34312538e-02,  2.33157203e-02,  1.39788510e-02, -1.30240815e-02,
       -2.42395885e-02, -8.30471143e-03,  1.18913641e-02,  1.38949342e-02,
       -8.03327840e-03, -1.89843141e-02,  3.91115695e-02,  8.15670472e-03,
        2.35962472e-03, -2.66484171e-02, -3.99145298e-02, -2.65235244e-03,
       -7.89295975e-03, -3.50250788e-02, -5.02503067e-02,  2.16018017e-02,
       -7.41655603e-02,  2.49898201e-03, -2.72420887e-02,  1.59034114e-02,
       -5.89107946e-02,  4.44511045e-03, -3.71399187e-02,  5.91110848e-02,
       -2.02568416e-02, -4.26044352e-02,  1.13537908e-03,  3.92020941e-02,
        1.46575440e-02, -7.35081956e-02, -9.65632219e-03,  2.97093298e-03,
       -1.39750373e-02,  8.40857904e-03,  1.80709618e-03,  5.49090700e-03,
        4.68099825e-02, -2.53207982e-02,  1.59446783e-02,  8.97399709e-02,
       -2.62675751e-02, -2.81816274e-02, -5.46947531e-02, -1.94827153e-04,
       -4.83741015e-02, -5.62165538e-03, -1.86006278e-02, -1.95679013e-02,
       -1.47121465e-02,  1.77136008e-02,  2.88326368e-02,  3.61421518e-02,
        4.95872498e-02,  5.42055927e-02,  5.85496314e-02,  9.08739772e-03,
        2.90538054e-02, -1.33304074e-02, -6.62292615e-02, -8.02871399e-03,
       -2.36920044e-02,  3.42302211e-02,  5.37409168e-03, -3.09885405e-02,
        1.98077988e-02, -1.21544497e-02,  1.63462721e-02, -3.79285440e-02,
       -3.22538204e-02, -1.06495665e-02,  6.77168695e-03, -1.44041958e-04,
       -6.61448017e-02, -3.55255343e-02,  3.89818363e-02, -2.97151227e-02,
       -7.84883052e-02, -4.36381586e-02, -9.63150244e-03, -1.76280923e-02,
        2.93803308e-03, -5.29805105e-03, -5.94426095e-02, -3.20506580e-02,
       -1.24090398e-02, -8.87059607e-03, -7.73281157e-02,  2.95962356e-02,
       -1.57814324e-02,  5.30786021e-03, -5.84073178e-02,  3.05691082e-02,
        6.75613852e-03,  2.98029389e-02,  3.06674745e-02,  6.28118962e-02,
        2.07693558e-02, -1.19009335e-02,  4.11018431e-02,  7.82713369e-02,
        2.47066524e-02, -4.15725335e-02, -2.45792791e-02,  3.86853218e-02,
       -4.28122748e-03,  1.88907627e-02, -5.87618165e-02, -1.23007856e-02,
       -3.75858210e-02, -6.39905361e-03, -1.08416444e-02,  2.74249204e-02,
        2.60703266e-02,  1.89379454e-02, -1.48278037e-02, -5.03423996e-03,
        2.98529752e-02,  2.37675551e-02,  6.77957246e-03, -5.51808439e-03,
        2.68877000e-02,  4.38492596e-02, -3.07156728e-03,  2.82602254e-02,
        1.98453553e-02, -9.36900917e-03,  3.90419294e-03,  1.75918136e-02,
        3.08590606e-02,  5.64047396e-02, -2.25785580e-02, -3.07163261e-02,
        2.93382294e-02,  1.95369907e-02, -3.01936772e-02,  6.95509240e-02,
       -2.08426476e-03,  1.71886608e-02, -2.01387778e-02,  2.21506059e-02,
       -1.22746802e-04,  1.29205929e-02, -2.80680750e-02, -6.13656864e-02,
        5.53723276e-02, -3.38710472e-02, -2.90389974e-02, -2.50181016e-02,
        5.24298437e-02,  1.98607389e-02,  6.59221858e-02, -2.93972399e-02,
       -5.36284596e-02, -4.74941498e-03, -4.83085141e-02,  2.33445056e-02,
       -1.88582186e-02, -1.89028997e-02,  8.36170465e-02, -1.39654353e-02,
        6.99756220e-02,  3.54811968e-03, -4.17486057e-02, -4.76693474e-02,
        3.10532004e-02,  1.44475373e-02,  6.13843426e-02, -5.21905795e-02,
       -4.54106368e-02,  3.25982273e-02,  2.52038408e-02,  1.94381662e-02,
        3.81245874e-02,  3.78687605e-02, -2.46389071e-03, -2.22481904e-03,
       -6.12265691e-02,  1.02571342e-02,  2.43136659e-02, -4.96467054e-02,
       -9.80472006e-03,  3.48265134e-02, -1.16648274e-02, -3.96973938e-02,
        1.45285064e-02, -3.00802421e-02,  2.55046971e-03,  3.57069373e-02,
        1.28952730e-02, -1.21345008e-02,  3.65680307e-02, -7.49947205e-02,
        4.27749148e-03, -2.88607422e-02, -1.14321578e-02, -5.01228347e-02,
        1.77563000e-02,  1.12667024e-01,  1.71386208e-02, -2.94583067e-02,
        1.81442704e-02, -4.24720021e-03, -3.67747545e-02, -3.92848514e-02,
       -2.90525630e-02, -2.75519267e-02, -4.63064611e-02,  7.48809241e-03,
       -2.20187511e-02, -2.94989850e-02,  6.78180456e-02, -2.44643688e-02,
       -5.28920908e-03,  5.08467890e-02, -5.89218289e-02,  1.16211474e-02,
        5.58772497e-02, -1.67921372e-02,  2.51824241e-02, -1.03653371e-02,
       -2.82233872e-04, -1.05740875e-02,  1.26876198e-02, -1.94501728e-02,
        8.56874213e-02, -2.48915087e-02, -7.18868850e-03, -2.54455879e-02,
        1.06760010e-03, -1.16640457e-03,  9.18938816e-02,  1.52521217e-02,
       -9.00327042e-02,  3.38021666e-02,  1.13029499e-02,  1.29609862e-02,
       -2.28059907e-02, -7.34088197e-02, -4.81783040e-02, -1.63566377e-02,
        3.48034613e-02,  5.99057064e-04,  2.14459933e-02,  3.02965865e-02,
       -6.05289172e-03, -3.98056163e-03,  1.39752058e-02, -1.74115703e-03,
        7.03254640e-02,  6.99278340e-03, -6.02800883e-02, -1.75951812e-02,
        2.05654465e-02,  2.72583384e-02, -5.81133440e-02, -4.43419740e-02,
        6.67489658e-04, -6.03015721e-02,  4.17084666e-03, -1.59151629e-02,
       -6.27575219e-02,  5.24654277e-02,  5.56632504e-02,  4.07385193e-02,
       -4.68502454e-02, -2.31056102e-02,  2.92017255e-02, -3.37896161e-02,
       -1.08980173e-02,  1.39802843e-02,  4.10385709e-03, -2.45429706e-02,
       -3.62788071e-03,  3.16786766e-02,  1.61707797e-03,  2.67666150e-02,
       -1.60092227e-02, -5.48988841e-02,  1.74521822e-02, -2.04226729e-02,
       -2.44326726e-01,  1.64353102e-02, -1.40350005e-02, -2.13201568e-02,
        1.94494408e-02, -8.69541429e-03, -7.75015447e-03, -3.13187167e-02,
        8.98336340e-03,  1.09414442e-03, -1.87220182e-02, -5.29703945e-02,
        1.97308674e-03,  3.98124196e-02,  4.06799875e-02,  5.89337908e-02,
        8.79016519e-03, -2.86260098e-02,  1.63354483e-02,  4.30044048e-02,
        2.94392165e-02, -6.81872889e-02, -6.21845573e-03,  6.75897226e-02,
       -5.17551787e-02,  5.13402596e-02, -3.52780409e-02, -3.31724137e-02,
       -7.96146020e-02, -1.76516157e-02, -4.46428033e-03,  1.27226394e-02,
        8.30856804e-03,  8.47584859e-04,  2.26863772e-02, -1.96255837e-02,
        4.22096662e-02, -2.86644083e-02, -6.55350387e-02,  2.41784025e-02,
       -6.63983226e-02, -4.14943323e-02,  4.62108757e-03, -4.15855125e-02,
        4.73546796e-02,  6.30559865e-03,  4.09171870e-03, -3.41387652e-02,
       -4.10302281e-02,  2.63617225e-02, -3.06181833e-02, -2.22142674e-02,
        3.55439074e-02,  2.04827674e-02, -7.79355783e-03, -3.18791568e-02,
       -1.55708902e-02,  2.98418514e-02, -4.56394553e-02, -1.11822430e-02,
       -3.72135779e-03, -5.00356406e-02,  2.12778291e-03, -7.58925406e-03,
       -5.33041209e-02, -6.65694522e-03, -4.23851237e-02, -3.21049765e-02,
        4.24179770e-02,  4.68809083e-02, -9.90601629e-03,  4.05084267e-02,
       -3.50202061e-02, -6.93702325e-02, -5.48793748e-03, -2.44333353e-02,
        4.06132778e-03, -6.84386957e-03,  2.35699117e-02, -3.11924219e-02,
       -6.15332276e-02, -4.96733226e-02, -6.82910671e-03,  3.32778916e-02,
       -1.26644401e-02, -7.18913749e-02, -2.40416713e-02, -5.17467074e-02,
       -2.43038926e-02, -3.10121216e-02,  6.64348304e-02, -3.36398073e-02,
        3.36237140e-02,  5.04448153e-02,  2.42521130e-02,  7.05718994e-02,
        3.36492732e-02,  3.73037979e-02,  5.19505236e-03,  5.10926777e-03,
        5.56115061e-03, -3.68187055e-02,  2.43540257e-02,  4.41630231e-03,
       -1.08684497e-02, -2.40572816e-04, -2.80700647e-03,  3.22514214e-02,
        5.78009672e-02, -3.00332643e-02, -4.76387283e-03,  2.28127316e-02,
       -5.25155896e-03,  6.37290254e-03,  6.11524396e-02, -2.67515816e-02,
        2.43464559e-02,  1.81490686e-02,  1.75828375e-02, -1.24046281e-02,
       -6.90323636e-02,  1.15497475e-02, -2.98537165e-02,  1.67653337e-02,
       -6.54491186e-02, -3.27107869e-02,  9.95344855e-03,  3.19215208e-02,
        3.41796987e-02,  8.41484591e-03,  8.87995400e-03, -5.62823727e-04,
        2.37927083e-02, -1.24146007e-02,  2.98286844e-02, -1.86214782e-02,
       -1.82892960e-02, -1.06599014e-02, -4.82757017e-02,  1.02231288e-02,
        1.65076498e-02, -4.98858979e-03, -3.22775729e-02,  2.90716179e-02,
       -9.12267063e-03,  3.56022827e-02,  8.39754101e-03,  5.12932707e-03,
       -5.51234335e-02,  2.11954042e-02,  2.68297438e-02,  1.47314668e-02,
        2.84002163e-02, -2.53322218e-02, -4.93493602e-02,  7.01275766e-02,
        8.70494917e-03, -1.27310737e-03, -5.47257485e-03, -6.60896450e-02,
        2.75537185e-02,  1.47313550e-02,  1.75253637e-02, -2.78602690e-02,
       -2.61997618e-02,  1.01500889e-02, -2.55666394e-02,  7.83308875e-03,
        9.52804554e-03,  5.93859032e-02,  4.45680693e-02,  1.11198542e-03,
       -1.45276496e-03,  5.60957231e-02, -2.00713575e-02, -5.06374948e-02,
        1.84300600e-03,  1.58001482e-02, -4.76707034e-02,  3.21472622e-02,
        1.08266238e-03, -8.39598104e-03, -1.94403492e-02,  4.49814722e-02,
        5.91486022e-02,  1.43322926e-02, -8.80525727e-03, -3.50525789e-02,
       -7.89965130e-03, -4.56671380e-02,  2.07088087e-02, -3.03986445e-02,
        2.46905237e-02, -3.05276234e-02, -4.58035842e-02, -6.03824370e-02,
       -1.88502092e-02,  1.25131998e-02, -1.91772040e-02, -2.68140323e-02,
       -1.13334293e-02, -9.20215622e-03, -2.86374544e-03, -1.87009908e-02,
        5.55773750e-02, -5.71877323e-02,  1.20153045e-02, -1.16040194e-02,
        7.02821761e-02,  1.78125948e-02, -4.89550782e-03, -7.20467567e-02,
        1.28263729e-02, -2.60329340e-02, -3.85060981e-02,  8.31029471e-03,
       -2.30428576e-02,  4.73444611e-02,  2.74033789e-02, -6.69871718e-02,
       -1.91293936e-03, -2.45394595e-02,  5.00197336e-02, -3.69082503e-02,
        5.87179745e-03,  3.62827703e-02,  5.33243408e-03, -2.75677219e-02,
        3.87052186e-02, -6.47182539e-02,  2.19767354e-02, -3.64412926e-02,
        2.87303850e-02,  2.59774216e-02, -3.38106905e-03, -1.07798809e-02,
       -5.23210876e-02, -3.44884992e-02, -2.44131088e-02,  3.46138179e-02,
       -2.11323635e-03,  3.37004624e-02, -3.59658785e-02, -5.45871295e-02,
        1.03514744e-02,  1.39617710e-03,  7.15075508e-02, -6.74204975e-02,
       -2.33745109e-02,  6.81831017e-02, -4.10751253e-03,  2.34780032e-02,
        3.23863514e-03, -4.14933898e-02,  7.48998225e-02,  4.34612520e-02,
       -3.15943733e-02, -1.55308656e-02, -2.50037834e-02,  2.27680840e-02,
        1.78896007e-03,  1.03932042e-02, -3.10411416e-02,  5.84103167e-02,
        4.79346402e-02,  5.43241464e-02, -1.20849917e-02, -3.54509503e-02,
        4.03548107e-02,  1.31790424e-02,  2.64201481e-02, -4.70550135e-02,
       -1.32192522e-02,  2.88710948e-02,  1.70722939e-02, -4.19546552e-02,
       -3.02984230e-02,  8.68536159e-03,  4.98705395e-02, -4.03242968e-02,
       -3.32836211e-02,  2.20562164e-02,  2.77305823e-02,  2.77772117e-02,
        5.44738770e-02,  1.10938512e-02,  1.98466543e-04,  4.66421992e-02,
       -2.74618082e-02,  5.87482601e-02, -2.29810011e-02,  7.38234371e-02,
       -2.37538815e-02,  3.73214632e-02,  2.09433064e-02,  1.36870574e-02,
        5.18200807e-02,  6.23454414e-02,  3.51759121e-02,  9.71985888e-03,
       -2.67218128e-02,  2.58796904e-02,  4.32374142e-02, -2.80630845e-03,
       -5.87480068e-02,  5.17941006e-02, -1.42238503e-02, -3.28667201e-02,
        3.33039043e-03,  3.02480515e-02, -5.10340976e-03, -4.93807979e-02,
        3.65413539e-02,  1.58255305e-02, -7.49447476e-03,  2.85218135e-02,
       -3.23878415e-02, -6.42231852e-02,  1.54687492e-02,  5.48793143e-03,
       -3.66799682e-02, -1.31589232e-03,  6.20106570e-02, -1.03528425e-02,
       -9.48173832e-03,  7.64813051e-02, -1.42625002e-02, -3.00425179e-02,
        2.26328876e-02,  2.82362066e-02,  4.80139181e-02,  2.32902560e-02,
       -7.80071504e-03,  1.94764081e-02, -2.92048957e-02, -6.81131333e-02,
       -3.13237719e-02, -1.19036827e-02,  8.13037157e-02,  1.17536560e-02,
        1.18145999e-02,  6.97514117e-02,  6.00511134e-02,  4.36694510e-02,
       -2.17686985e-02,  3.33389528e-02,  1.44500481e-02,  3.86511348e-02,
        2.00069766e-03,  6.97316080e-02,  2.76505128e-02,  4.26333137e-02,
       -3.02640256e-02, -5.29407188e-02,  4.99677919e-02,  3.20329852e-02,
       -2.55737286e-02,  7.07087070e-02, -1.85213145e-02, -6.67810580e-03,
        4.35236730e-02,  6.04722202e-02,  6.09490834e-02, -1.86130125e-02,
       -7.50208125e-02,  6.34906767e-03,  3.47261392e-02, -3.44837159e-02,
       -2.45238785e-02,  5.74060120e-02, -4.51169396e-03,  2.80798096e-02,
       -2.68089436e-02, -1.31299831e-02, -5.52588664e-02, -9.42985062e-03,
       -1.57532394e-02,  2.33821031e-02, -7.41297333e-03,  3.31010707e-02,
        4.24777307e-02,  4.25020093e-03, -3.87272611e-02, -3.08711324e-02,
       -1.61017403e-02, -2.45526321e-02, -1.80568285e-02, -1.30702904e-03,
       -1.78097859e-02, -1.62484944e-02, -4.29858901e-02, -6.74154982e-02,
       -3.28838266e-02,  9.49180219e-03, -1.59086958e-02, -2.94311182e-03,
        4.42147627e-02,  7.87959397e-02,  3.53227817e-02,  4.80255205e-03,
        1.60864554e-02, -2.23202780e-02, -4.15852144e-02,  7.09676892e-02,
        1.63220465e-02,  4.19787318e-02,  3.29217017e-02, -3.23345289e-02,
       -4.81702536e-02, -1.48386899e-02,  4.11769934e-02,  1.20201111e-02,
       -3.83626074e-02,  2.97202319e-02,  2.06590667e-02,  1.17256902e-02,
        1.85967665e-02,  1.69150750e-04,  2.76333112e-02, -1.49556836e-02,
       -4.27177250e-02,  2.41764169e-02, -1.00354934e-02,  1.51842544e-02,
       -5.43640368e-02,  3.66863981e-02,  1.62881278e-02,  2.57299170e-02,
       -4.25983146e-02,  1.12327179e-02, -1.76163409e-02,  5.73693402e-03,
       -1.80702806e-02, -2.59304848e-02, -2.76248492e-02, -2.11273804e-02,
       -4.42449981e-03, -5.41407196e-03,  9.59399343e-03, -4.86853160e-02,
        1.22611066e-02, -3.44552356e-03, -4.26415913e-02,  3.44889276e-02,
       -2.41323151e-02, -7.84779061e-03, -7.30363354e-02, -4.35290560e-02,
       -2.99701337e-02,  2.20062286e-02, -3.52013446e-02,  3.21785323e-02,
       -1.98723841e-02, -8.62164743e-05, -1.66180599e-02, -3.62735987e-02,
        9.81293805e-03,  3.04788239e-02, -3.93488705e-02,  1.75341964e-02],
      dtype=float32)

In [20]:
from app.vector_store.index_docs import create_collection

create_collection()

Connecting to Qdrant
Collection Already Exists

In [11]:
from app.vector_store.index_docs import (
    create_collection,
    index_documents
)

from app.ingestion.creat_doc import create_documents

# temporary smoke test

create_collection()

# sample_docs = documents[:1000]

index_documents(documents)

print("Smoke Test Passed")

2026-06-28 11:06:28,849 | INFO | python_tutor_rag | Initializing Qdrant client...
Collection Already Exists
2026-06-28 11:06:28,960 | INFO | python_tutor_rag | Loading BGE model into memory...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

2026-06-28 11:06:30,674 | WARNING | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

2026-06-28 11:06:35,790 | INFO | python_tutor_rag | Model id: 17916279312

KeyboardInterrupt:

In [22]:
from app.retriever.retriever import retrieve


results = retrieve(
    "What is the difference between list and tuple?"
)

for r in results:
    print(r)
    print("=" * 100)

2026-06-27 21:52:16,805 | INFO | python_tutor_rag | Hybrid retrieval started for query: What is the difference between list and tuple?

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-27 21:52:17,183 | INFO | httpx | HTTP Request: POST http://localhost:6333/collections/stackoverflow_python/points/query "HTTP/1.1 200 OK"
2026-06-27 21:52:17,195 | INFO | python_tutor_rag | Retrieved 5 chunks
{'content': 'TITLE:\nWhat is the difference between @staticmethod and @classmethod in Python?\n\nQUESTION:\nWhat is the difference between a function decorated with\n[CODE]\n@staticmethod\n[/CODE]\nand one decorated with\n[CODE]\n@classmethod\n[/CODE]\n?', 'question_id': 136097, 'answer_id': 1669524, 'question_score': 1583, 'answer_score': 1256, 'source': 'stackoverflow', 'chunk_id': 0, 'parent_question_id': 136097}
====================================================================================================
{'content': "TITLE:\nWhat is the difference between Python's re.search and re.match?\n\nQUESTION:\nWhat is the difference between the\n[CODE]\nsearch()\n[/CODE]\nand\n[CODE]\nmatch()\n[/CODE]\nfunctions in the\nPython\n[CODE]\nre\n[/CODE]\nmodule\n?\nI've read the\ndocumentation\n(\ncurrent documentation\n), but I never seem to remember it.  I keep having to look it up and re-learn it.  I'm hoping that someone will answer it clearly with examples so that (perhaps) it will stick in my head.  Or at least I'll have a better place to return with my question and it will take less time to re-learn it.", 'question_id': 180986, 'answer_id': 180993, 'question_score': 189, 'answer_score': 209, 'source': 'stackoverflow', 'chunk_id': 0, 'parent_question_id': 180986}
====================================================================================================
{'content': "\nTITLE:\nWhat is the difference between range and xrange functions in Python 2.X?\n\nQUESTION:\nApparently xrange is faster but I have no idea why it's faster (and no proof besides the anecdotal so far that it is faster) or what besides that is different about\n[CODE]\nfor i in range(0, 20):\nfor i in xrange(0, 20):\n[/CODE]\n\nANSWER:\nrange creates a list, so if you do\n[CODE]\nrange(1, 10000000)\n[/CODE]\nit creates a list in memory with\n[CODE]\n9999999\n[/CODE]\nelements.\n[CODE]\nxrange\n[/CODE]\nis a sequence object that  evaluates lazily.\n", 'question_id': 94935, 'answer_id': 94962, 'question_score': 378, 'answer_score': 460, 'source': 'stackoverflow'}
====================================================================================================
{'content': "\nTITLE:\nWhat is the difference between __reduce__ and __reduce_ex__?\n\nQUESTION:\nI understand that these methods are for pickling/unpickling and have no relation to the reduce built-in function, but what's the difference between the 2 and why do we need both?\n\nANSWER:\nThe docs\nsay that\nIf provided, at pickling time\n[CODE]\n__reduce__()\n[/CODE]\nwill be called with no\narguments, and it must return either a\nstring or a tuple.\nOn the other hand,\nIt is sometimes useful to know the\nprotocol version when implementing\n[CODE]\n__reduce__\n[/CODE]\n. This can be done by\nimplementing a method named\n[CODE]\n__reduce_ex__\n[/CODE]\ninstead of\n[CODE]\n__reduce__\n[/CODE]\n.\n[CODE]\n__reduce_ex__\n[/CODE]\n, when it\nexists, is called in preference over\n[CODE]\n__reduce__\n[/CODE]\n(you may still provide\n[CODE]\n__reduce__\n[/CODE]\nfor backwards\ncompatibility). The\n[CODE]\n__reduce_ex__\n[/CODE]\nmethod will be called with a single\ninteger argument, the protocol\nversion.\nOn the gripping hand,\nGuido says\nthat this is an area that could be cleaned up.\n", 'question_id': 150284, 'answer_id': 150309, 'question_score': 9, 'answer_score': 16, 'source': 'stackoverflow'}
====================================================================================================
{'content': '\nTITLE:\nWhat is the difference between Ruby and Python versions of"self"?\n\nQUESTION:\nI\'ve done some Python but have just now starting to use Ruby\nI could use a good explanation of the difference between "self" in these two languages.\nObvious on first glance:\nSelf is not a keyword in Python, but there is a "self-like" value no matter what you call it.\nPython methods receive self as an explicit argument, whereas Ruby does not.\nRuby sometimes has methods explicitly defined as part of self using dot notation.\nInitial Googling reveals\nhttp://rubylearning.com/satishtalim/ruby_self.html\nhttp://www.ibiblio.org/g2swap/byteofpython/read/self.html\n\nANSWER:\nPython is designed to support more than just object-oriented programming. Preserving the same interface between methods and functions lets the two styles interoperate more cleanly.\nRuby was built from the ground up to be object-oriented. Even the literals are objects (evaluate 1.class and you get Fixnum). The language was built such that self is a reserved keyword that returns the current instance wherever you are.\nIf you\'re inside an instance method of one of your class, self is a reference to said instance.\nIf you\'re in the definition of the class itself (not in a method), self is the class itself:\n[CODE]\nclass C\nputs "I am a #{self}"\ndef instance_method\nputs \'instance_method\'\nend\ndef self.class_method\nputs \'class_method\'\nend\nend\n[/CODE]\nAt class definition time, \'I am a C\' will be printed.\nThe straight \'def\' defines an instance method, whereas the \'def self.xxx\' defines a class method.\n[CODE]\nc=C.new\nc.instance_method\n#=> instance_method\nC.class_method\n#=> class_method\n[/CODE]\n', 'question_id': 159990, 'answer_id': 160227, 'question_score': 6, 'answer_score': 7, 'source': 'stackoverflow'}
====================================================================================================

In [26]:
from app.retriever.load_bm25 import bm25_retriever

results = bm25_retriever.retrieve(
    "difference between append and extend",
    top_k=5
)

print(type(results[0]))
print(results[0])

<class 'dict'>
{'content': 'TITLE:\nWhat is the difference between @staticmethod and @classmethod in Python?\n\nQUESTION:\nWhat is the difference between a function decorated with\n[CODE]\n@staticmethod\n[/CODE]\nand one decorated with\n[CODE]\n@classmethod\n[/CODE]\n?', 'question_id': 136097, 'answer_id': 1669524, 'question_score': 1583, 'answer_score': 1256, 'source': 'stackoverflow', 'chunk_id': 0, 'parent_question_id': 136097}

In [25]:
from app.retriever.retriever import retrieve
results = retrieve(
    "difference between append and extend"
)

print(results[0])

2026-06-27 21:53:09,185 | INFO | python_tutor_rag | Hybrid retrieval started for query: difference between append and extend

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-27 21:53:10,041 | INFO | httpx | HTTP Request: POST http://localhost:6333/collections/stackoverflow_python/points/query "HTTP/1.1 200 OK"
2026-06-27 21:53:10,055 | INFO | python_tutor_rag | Retrieved 5 chunks
{'content': 'TITLE:\nWhat is the difference between @staticmethod and @classmethod in Python?\n\nQUESTION:\nWhat is the difference between a function decorated with\n[CODE]\n@staticmethod\n[/CODE]\nand one decorated with\n[CODE]\n@classmethod\n[/CODE]\n?', 'question_id': 136097, 'answer_id': 1669524, 'question_score': 1583, 'answer_score': 1256, 'source': 'stackoverflow', 'chunk_id': 0, 'parent_question_id': 136097}

In [34]:
from ddgs import DDGS

with DDGS() as ddgs:
    results = list(
        ddgs.text(
            "difference between decorator and itrerator python",
            max_results=3
        )
    )

print(results)

2026-06-27 22:22:59,612 | INFO | primp | response: https://en.wikipedia.org/w/api.php?action=opensearch&profile=fuzzy&limit=1&search=difference%20between%20decorator%20and%20itrerator%20python 200
2026-06-27 22:23:00,223 | INFO | primp | response: https://grokipedia.com/api/typeahead?query=difference+between+decorator+and+itrerator+python&limit=1 200
2026-06-27 22:23:01,078 | INFO | primp | response: https://www.google.com/search?q=difference+between+decorator+and+itrerator+python&filter=1&start=0&hl=en-US&lr=lang_en&cr=countryUS 200
[{'title': 'What are Iterators, Generators And Decorators in Python?', 'href': 'https://rishikonapure.medium.com/what-are-iterators-generators-and-decorators-in-python-d3f9064184c6', 'body': '13 Apr 2022 · A decorator in Python is any callable Python object that is used to modify a function or a class. It takes in a function, adds some ...'}, {'title': 'Python Iterators and Generators Tutorial - DataCamp', 'href': 'https://www.datacamp.com/tutorial/python-iterators-generators-tutorial', 'body': 'Iterators are objects that can be iterated upon. They serve as a common feature of the Python programming language, neatly tucked away for looping and list ...Exploring Python iterables with... · Python Generators'}, {'title': 'Generators and Decorators - Online IT Guru', 'href': 'https://onlineitguru.com/tutorials/generators-and-decorators', 'body': '15 Jun 2020 · A decorator is a python interesting features that add functionality to the existing code. This is also called metaprogramming. Decorators are ...'}]